In [2]:
#import required packages for this numpy exercise
import numpy as np

#### 1. Create a 3x3x3 array with random values

In [13]:
#Numpy built-in function random.rand takes dimensions as parameters and generate the array with given dimensions
#Here we need 3X3X3 matrix. So giving the below command will generate the matrix
print(np.random.rand(3,3,3))

[[[0.92771557 0.7869898  0.01662198]
  [0.95743238 0.02641067 0.57664606]
  [0.87663034 0.88008381 0.76010221]]

 [[0.56070108 0.31037766 0.51988525]
  [0.00625692 0.61899958 0.01243829]
  [0.34127299 0.21229527 0.89220321]]

 [[0.44632044 0.27747062 0.06041538]
  [0.08552869 0.09210196 0.19018752]
  [0.32787047 0.83524735 0.62672569]]]


#### 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
#lets create the array of 5X5 with full of zeros
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:
#lets create another 1-d array from 0 to 3. np.arange function will sort this out. 
#This array is required to replace the elements of diagonal just below the main diagonal of matrix 
#with numbers 1,2,3,4.
v = np.arange(4)

#lets add the above 1-d array to number 1 and print the output
v_upd = v + 1
print(v_upd)

[1 2 3 4]


In [5]:
#using numpy's function np.diag(), we can replace the above 1-d array into that zero's matrix
# np.diag() will take two parameters.
# 1. v: If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.
# 2. k: Diagonal in question. The default is 0.  k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

Z = np.diag(v_upd, k=-1) #k=-1, for elements just below the diagnoal and those elements are getting replaced with new array v_upd
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
# For moment of understanding, Let's create a 8X8 matrix using np.arange() function
my_arr = np.arange(64).reshape(8,8) #reshape Gives a new shape to an array without changing its data
print(my_arr)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [11]:
# Using slicing notation, we can grab the required rows and columns and fill it with desired values
# Lets see what is the output when 1::2 slicing is applied on above matrix 
print(my_arr[1::2])

[[ 8  9 10 11 12 13 14 15]
 [24 25 26 27 28 29 30 31]
 [40 41 42 43 44 45 46 47]
 [56 57 58 59 60 61 62 63]]


In [18]:
# Its gave 1st, 3rd, 5th and 7th rows when 1::2 slicing is applied on above.
# Lets see what ::2 slicing gives as an output
print(my_arr[::2])

[[ 0  1  2  3  4  5  6  7]
 [16 17 18 19 20 21 22 23]
 [32 33 34 35 36 37 38 39]
 [48 49 50 51 52 53 54 55]]


In [13]:
#It produced 0th, 2nd, 4th and 6th rows
# lets apply both slicing notations and see
print(my_arr[1::2, ::2])

[[ 8 10 12 14]
 [24 26 28 30]
 [40 42 44 46]
 [56 58 60 62]]


In [14]:
# here 8 is from 1st row and 0th column(1,0), similarly 10,12,14 came from (1,2),(1,4) and (1,6)
#lets see if we revers the slicing notations
print(my_arr[::2, 1::2])

[[ 1  3  5  7]
 [17 19 21 23]
 [33 35 37 39]
 [49 51 53 55]]


In [17]:
#Now it is clear that 1::2 and ::2 is required slicing notations for checkerboard pattern
#Lets create a function to repeat this task

def checkerPattern(n):
    
    Z = np.zeros((n,n))
    Z[1::2, ::2] = 1
    Z[::2, 1::2] = 1
    print(Z)

checkerPattern(8)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 4. Normalize a 5x5 random matrix

In [7]:
# lets define a 5X5 array and assign it to a variable
array = np.random.rand(5,5)
print("Original Array: ")
print()
print(array)
print()

#compute the maximum and minimum values of above array 
#and assign it to variables xmax and xmin
xmax, xmin = array.max(), array.min()

#Now normalised form of an array is defined as an array 
#where dividing every entry in a vector by its magnitude to create a vector of length 1
norm = (array - xmax)/(xmax - xmin) #normalised form


#print the resultabs
print("After normalization: ")
print()
print(norm)

Original Array: 

[[0.61400411 0.27808597 0.31366132 0.51032121 0.41534103]
 [0.64761392 0.16229493 0.87861671 0.85117664 0.59288878]
 [0.04021083 0.98430388 0.72593409 0.86127077 0.08207169]
 [0.07086213 0.47307128 0.8361082  0.14569118 0.37708781]
 [0.97852401 0.81450936 0.66884676 0.14751251 0.20275144]]

After normalization: 

[[-0.39222805 -0.74803846 -0.71035642 -0.50205079 -0.60265548]
 [-0.35662794 -0.87068637 -0.11194571 -0.14101072 -0.41459378]
 [-1.          0.         -0.27366984 -0.13031884 -0.95566024]
 [-0.96753361 -0.54150658 -0.15697148 -0.88827335 -0.64317396]
 [-0.00612213 -0.17984934 -0.33413774 -0.88634416 -0.82783412]]


#### 5. How to find common values between two arrays?

In [31]:
#Lets create a function that accepts two arrays as arguments
#The logic is such a way that the function should print true and values if common values are found in both arrays


def commonChecker(a,b):
    
    cValues = [] #Defining an empty list so that whenever common values are found, value should be appended.
    
    for x in a:
        if x in b:
            cValues.append(x)
    print("Common values exist. Values are:\n")
    print(cValues)

commonChecker(np.array([5,7,8,9,10]), np.array([7,10,15,8,47]))

Common values exist. Values are:

[7, 8, 10]


#### 6.How to get the dates of yesterday, today and tomorrow?

In [39]:
#Numpy's in-built datetime and timedelta methods can help to sort this out

#lets print today's date
print(np.datetime64('today'))

2020-07-25


In [35]:
#timedelta function is used to print date by n units forward, backward.
print(np.timedelta64(1))

1 generic time units


In [36]:
#To print tomorrow's date
print(np.datetime64('today') + np.timedelta64(1))

2020-07-26


In [37]:
#To print yesterday's date
print(np.datetime64('today') - np.timedelta64(1))

2020-07-24


In [38]:
#so on combined notation
#yesterday
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yesterday's date: ", yesterday)

#today
today = np.datetime64('today')
print("Today'date: ", today)

#tomorrow
tomorrow = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow's date: ", tomorrow)

Yesterday's date:  2020-07-24
Today'date:  2020-07-25
Tomorrow's date:  2020-07-26


#### 7. Consider two random array A and B, check if they are equal

In [22]:
#We can use a function that accepts two array
#the logic is to print true if element wise and length wise arrays are equal 

def arrayEqual(a,b, n, m):
    
    #check if lengths of both arrays are equal
    if(n != m):
        return False
    
    
    #sort the arrays
    a.sort()
    b.sort()
    
    #Check if element wise arrays are equal 
    for i in range(0, n):
        if(a[i] != b[i]):
            return False
    return True

#Driver code
a = np.array([8,7,1,5,3])
b = np.array([4,2,7,5,8])
n = len(a)
m = len(b)

#print success message if arrays are equal
if (arrayEqual(a,b,m,n)):
    print("Checking......")
    print("Arrays are equal!")
else:
    print("Checking......")
    print("Arrays are not equal")

Checking......
Arrays are not equal


In [20]:
#driver code
a = np.array([8,7,1,5,3])
b = np.array([3,8,5,1,7])
n = len(a)
m = len(b)

#print success message if arrays are equal
if (arrayEqual(a,b,m,n)):
    print("Checking......")
    print("Arrays are equal!")
else:
    print("Checking......")
    print("Arrays are not equal")

Checking......
Arrays are equal!


#### 8. Create random vector of size 10 and replace the maximum value by 0

In [52]:
#lets create a function that replaces maximum value of array by 0.
def replacerArray(a):
    
    #assign max element to variable
    max_elem = max(a)
    
    #generate a  loop such that maximum value replaces with zero
    for i in range(0, len(a)+1):
        if max_elem == a[i]:
            a[i] = 0
            break
    print(a)
            
#Driver code
a = np.random.rand(10)

#print the results before and after replacement
print("Original Array:\n")
print(a)
print()
print("Array after doing replacement:\n")
replacerArray(a)

Original Array:

[0.1675809  0.18440043 0.50581113 0.47745381 0.57170568 0.17013296
 0.23356333 0.63957802 0.85026322 0.6228952 ]

Array after doing replacement:

[0.1675809  0.18440043 0.50581113 0.47745381 0.57170568 0.17013296
 0.23356333 0.63957802 0.         0.6228952 ]


#### 9. How to print all the values of an array?

In [58]:
# lets create the function that prints all the values of an array
def allValues(a):
    
    #generating a loop to print all values
    print("Values of an given array:\n")
    for x in a:
        print(x, end=",")

#driver code
a = np.random.rand(10)

#printing the results
print("Given array:\n")
print(a)
print()
allValues(a)

Given array:

[0.51088732 0.49000806 0.71243427 0.94613081 0.15147324 0.55387497
 0.21173698 0.02637122 0.20770709 0.99946052]

Values of an given array:

0.5108873163194139,0.490008057066598,0.7124342691785842,0.946130809825234,0.15147324291181818,0.5538749726693832,0.21173698104898364,0.026371222741119027,0.20770709260085485,0.9994605173263724,

#### 10.Subtract the mean of each row of a matrix

In [90]:
#Lets create a function that computes the
#subtraction of mean value of each row from its value

def subtractMean(m,n):
    #create an array using m and n values
    _array = np.random.rand(m,n)
    print("Given array:\n")
    print(_array)
    print()
    
    #generate loop that do subtraction of mean value of each row from matrix
    for i in range(0, _array.shape[0]):
        print("Mean value of ",_array[i],"is: ", _array[i].mean())
        print("Subtracting the ",_array[i].mean(), "from ", _array[i], "gives:" )
        print(_array[i] - _array[i].mean())
        print()
    
    print("After doing subtraction, matrix is:\n")
    for i in range(0, _array.shape[0]):
        Y= _array[i] - _array[i].mean()
        print(Y)


subtractMean(3,4)

Given array:

[[0.72065918 0.44048119 0.03465498 0.29907166]
 [0.72208985 0.64831286 0.62437448 0.99020172]
 [0.57993728 0.8647838  0.35706647 0.89455264]]

Mean value of  [0.72065918 0.44048119 0.03465498 0.29907166] is:  0.37371675202115917
Subtracting the  0.37371675202115917 from  [0.72065918 0.44048119 0.03465498 0.29907166] gives:
[ 0.34694242  0.06676444 -0.33906177 -0.07464509]

Mean value of  [0.72208985 0.64831286 0.62437448 0.99020172] is:  0.746244728142144
Subtracting the  0.746244728142144 from  [0.72208985 0.64831286 0.62437448 0.99020172] gives:
[-0.02415487 -0.09793187 -0.12187025  0.24395699]

Mean value of  [0.57993728 0.8647838  0.35706647 0.89455264] is:  0.6740850451913366
Subtracting the  0.6740850451913366 from  [0.57993728 0.8647838  0.35706647 0.89455264] gives:
[-0.09414777  0.19069875 -0.31701858  0.2204676 ]

After doing subtraction, matrix is:

[ 0.34694242  0.06676444 -0.33906177 -0.07464509]
[-0.02415487 -0.09793187 -0.12187025  0.24395699]
[-0.09414777 

#### 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [111]:
#Code Credits:Bartosz Telenczuk
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z,I,1)
print(Z)

[3. 4. 6. 2. 1. 3. 2. 2. 5. 2.]


In [6]:
#Create a function that adds one to the values of first vector which are indexed by second vector

def helpingFunc(a):
    #define the indices of 'a' vector
    b = np.random.randint(a)
    
    #print the vectors created 'a' and 'b'
    print("Vector A taken from user:\n", a)
    print()
    print("Vector B which stores the indices of A:\n", b)
    print()
    
    #lets create an empty list
    c=[] 
    
    #Sort the 'b' vector 
    b.sort()
    
    #generate a loop that removes duplicates of 'b' vector
    for x in b:
        if x not in c:
            c.append(x)
    
    #generate a loop that adds 1 to values of 'a' vector at indices stored in modified b vector
    #which is list c
    for y in c:
        a[y] += 1
    print("After adding 1 at indices stored in b vector, the vector A becomes:\n", a)
    print()


a = np.random.randint(1,8,8)
helpingFunc(a)

Vector A taken from user:
 [1 4 4 5 4 3 1 2]

Vector B which stores the indices of A:
 [0 3 1 2 0 0 0 1]

After adding 1 at indices stored in b vector, the vector A becomes:
 [2 5 5 6 4 3 1 2]



#### 12.How to get the diagonal of a dot product?

In [120]:
#lets create a function that generates dot product and produces the diagonal

def diagDotProd(a,b):
    
    #Print the given array
    print("Matrix A:\n")
    print(a)
    print("Matrix B:\n")
    print(b)
    print()
    
    
    #Compute the dot product
    c = np.dot(a,b)
    print("Dot product of above matrices is:\n")
    print(c)
    print()
    
    #print the diagonal 
    k = np.diag(c)
    print("Diagonal:\n", k)
    print()
    

#driver code
a = np.random.randint(0,10,(3,3)) 
b = np.random.randint(0,10,(3,3))

#print the result
diagDotProd(a,b)

Matrix A:

[[8 6 3]
 [7 2 8]
 [5 5 1]]
Matrix B:

[[1 0 4]
 [7 6 6]
 [6 1 1]]

Dot product of above matrices is:

[[68 39 71]
 [69 20 48]
 [46 31 51]]

Diagonal:
 [68 20 51]



#### 13.How to find the most frequent value in an array?

In [143]:
#Define an array
x = np.random.randint(0, 10, 40)

#print the original arraya
print("Original array:")
print(x)

#print the most frequent array by using python in-built function np.bincount()
#argmax() Returns the indices of the maximum values along an axis 
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[0 7 3 8 1 9 4 8 6 9 6 7 2 5 7 4 7 6 6 3 5 9 1 9 8 8 5 6 6 6 6 1 4 4 6 9 8
 8 3 0]
Most frequent value in the above array:
6


#### 14.How to get the n largest values of an array

In [152]:
#create a function that takes two parameters array and n value to print n largest values
def nLargest(a, n):
    
    #print the given array  
    print("Original Array:\n")
    print(a)
    print()
    
    #shuffling using np.shuffle() which shuffles the array along the first axis of a multi-dimensional array.
    np.random.shuffle(a)
    
    #print the n largest values using argsort which returns an array of indices of the same shape as arr 
    #that that would sort the array
    print(n, "largest numbers of above array:\n")
    print(a[np.argsort(a)[-n:]])
    

a = np.arange(20)
n=2
nLargest(a, n)

Original Array:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

2 largest numbers of above array:

[18 19]


#### 15. How to create a record array from a regular array?

In [153]:
#Code Credits: numpy documentation and w3resource
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
